### ISSUE TITLE
InvalidArgumentException working with Cake\Chronos\MutableDateTime

### ISSUE THREAD

**Issue by steinkel** [opis/closure#31]
Hi,

We've been experiencing random issues with the following stack trace

```
2019-05-09 10:19:25 Error: [InvalidArgumentException] Unknown setter 'date'
#0 [internal function]: Cake\Chronos\MutableDateTime->__set('date', '2019-05-09 10:1...')
#1 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(398): ReflectionProperty->setValue(Object(Cake\I18n\Time), '2019-05-09 10:1...')
#2 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(358): Opis\Closure\SerializableClosure::wrapClosures(Object(Cake\I18n\Time), Object(Opis\Closure\ClosureScope))
#3 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(358): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#4 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(358): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#5 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(358): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#6 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(358): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#7 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(396): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#8 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(396): Opis\Closure\SerializableClosure::wrapClosures(Object(CakeDC\Workflow\Context\TransitionContext), Object(Opis\Closure\ClosureScope))
#9 /project/20190509100924/vendor/opis/closure/src/SerializableClosure.php(396): Opis\Closure\SerializableClosure::wrapClosures(Object(App\Form\Application\CommonTermsForm), Object(Opis\Closure\ClosureScope))
#10 /project/20190509100924/vendor/opis/closure/functions.php(19): Opis\Closure\SerializableClosure::wrapClosures(Object(CakeDC\Workflow\TransitionResults\TransitionFormExecutedResult))
```

while working with the serialization of a Cake\Chronos\MutableDateTime object https://github.com/cakephp/chronos/blob/1.2.5/src/MutableDateTime.php 

I've seen similar issues here https://github.com/botman/botman/issues/952 referring to a problem with opis/closure, could you confirm this issue will be solved downgrading to 2.* ?

Thanks,

**Comment by steinkel** [comment]
^ Using opis/closure 3.1.6

**Comment by msarca** [comment]
First of all, since we are using semantic versioning, downgrading is almost always a bad idea, because it means that you will most certainly use a more buggy and incomplete version of the library. Moreover, we do no longer provide support for the 2.x series.

Secondly, the issue you are describing here has nothing to do with opis/closure, but rather with the cake/chronos library and the way PHP is implementing `DateTime`. Let's take the following example:

```php
class Foo extends DateTime
{

}

$date = new Foo();
var_dump($date);
/*
object(Foo)#3 (3) {
  ["date"]=>
  string(26) "2019-05-09 20:25:09.569283"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
*/
```
As we can see, the `DateTime` class dynamically declares 3 new properties: `date`, `timezone_type`, and `timezone`. These 3 new properties, declared at run-time, have a special behavior: they cannot be overwritten by user.

```php
$date = new Foo();
$date->date = 'bar';
var_dump($date);
/*
object(Foo)#3 (3) {
  ["date"]=>
  string(26) "2019-05-09 20:25:09.569283"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
*/
```
Now, let's see how cake/chronos treats this situation and where the exception come from
```php
$date = new MutableDateTime();
$date->date = 'bar';
/*
Fatal error: Uncaught InvalidArgumentException: Unknown setter 'date' 
*/
```
This can be easily fixed inside `Cake\Chronos\MutableDateTime::__set` by handling the case when the property set by the user is `date` or `timezone_type` (`timezone` is already handled [here](/cakephp/chronos/blob/1.2.5/src/MutableDateTime.php#L161)).

```php
switch ($name) {
    // ... 
    case 'date':
    case 'timezone_type':
        $this->{$name} = $value; // This is important!
        break;
    // ...
}
```

**Comment by steinkel** [comment]
that's a very quick and helpful response, thank you. I'll be working on a PR to chronos soon.
